### ISSUE TITLE
[Bug] Resolve dependency - psr/simple-cache v2.0 - Laravel 9.x

### ISSUE THREAD

**Issue by gunmanix** [DirectoryTree/LdapRecord#564] opened 2023-03-01 07:42 UTC
With Laravel 9.x installation, there is a conflict in dependencies.

    laravel require: "psr/simple-cache": "^1.0|^2.0|^3.0",
    LdapRecord require: "psr/simple-cache": "^1.0|^2.0",

Please resolve this conflict, if it is possible.

--

composer message:

 Problem 1
    - Root composer.json requires directorytree/ldaprecord ^2.20 -> satisfiable by directorytree/ldaprecord[v2.20.0, v2.20.1, v2.20.2].
    - directorytree/ldaprecord[v2.20.0, ..., v2.20.2] require psr/simple-cache ^1.0|^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require directorytree/ldaprecord:*" to figure out if any version is installable, or "composer require directorytree/ldaprecord:^2.1" if you know which you need.

**Comment by stevebauman** [comment] 2023-03-01 13:10
Duplicate of https://github.com/DirectoryTree/LdapRecord-Laravel/issues/392.

**Closed** 2023-03-01 13:10 UTC
Labels: bug
