### ISSUE TITLE
orWhere returns unexpected results

### ISSUE THREAD

**Issue by derleder** [DirectoryTree/LdapRecord#133] opened 2020-05-13 08:19 UTC
**Describe the bug**
My users should search a certain user by a term that can be contained in multiple attributes. I'd like to use the Model methods that are said to be built on the query builder [here](https://ldaprecord.com/docs/models/#retrieving-models) such as whereContains() and orWhereContains(). As long as I only use whereContains() the results are as expected. But once I add orWhereContains() no results are returned at all. The same goes for simple where() and orWhere().

**To Reproduce**
```
$results1 = \LdapRecord\Models\ActiveDirectory\User::whereContains('givenname', $term)
            ->limit(5)
            ->get();

$results2 = \LdapRecord\Models\ActiveDirectory\User::whereContains('givenName', $term)
            ->orWhereContains('samaccountname', $term)
            ->limit(5)
            ->get();
```

When searching for a given name $results1 contains 5 valid entries. $results2 returns nothing. Even when the term matches a samaccountname and thus $results1 rightfully has no items $results2 is still empty.

**Expected behavior**
$results2 must have at least 5 items when $results1 has.

**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.2
 - LdapRecord: 1.7 (1.5.2 also)

**Comment by stevebauman** [comment] 2020-05-13 14:04
Hi @stevebauman,

This is what you're looking for:

```php
$users = User::orFilter(function ($query) use ($term) {
    $query->whereContains('givenname', $term)
        ->orWhereContains('samaccountname, $term);
})->limit(5)->get();
```

This will also work, but will not return `User` models:

```php
use LdapRecord\Models\ActiveDirectory\Entry;

$users = Entry::whereContains('givenName', $term)
    ->orWhereContains('samaccountname', $term)
    ->limit(5)
    ->get();
```

Why does the `User` model differ? Well, because constraints are automatically added to new queries generated from `User` models, so only Active Directory users are returned.

While the query builder is similar to Laravel's Eloquent, LDAP is extremely different in how objects are retrieved from a directory.

If we were to compare a database to an LDAP directory, every single object in your directory would be contained inside of a single `objects` database table:

```sql
select * from objects
```

This differs from Eloquent. Each Eloquent model ties to individual database tables, allowing you to query only those entries.

Retrieving LDAP users via a `User::get()` adds constraints to the LDAP filter, which can be visualized as the following SQL:

```php
select
    *
from
    objects
where
    objectclass in ( 'top', 'person', 'organizationalperson', 'user') and
    objectclass not in ('computer');
```

Now that you can see the constraints visually, you can guess that this becomes pretty complicated if we were to somehow guess developer intention when calling query filter methods.

Hope this makes sense! Closing this, as it's not a bug -- but feel free to comment back if you'd like to know more.

Thanks!

**Closed by stevebauman** 2020-05-13 14:04 UTC
Labels: question

**Comment by derleder** [comment] 2020-05-14 08:53
Since I don't use Laravel but Cake I got lost a little in the middle but considering the nature of LDAP filters there had to be a catch somewhere in trying to apply relational query knowledge to it. Your suggestion did the trick! So thanks for that and for abstracting LDAP in such a great way (and sorry for the dramatic subject. It looked too much like a dead end back then)
