### ISSUE TITLE
[Bug] Cannot modify an arbitrary attribute on an Active Directory User object

### ISSUE THREAD

**Issue by nspaul** [DirectoryTree/LdapRecord#398] opened 2022-02-16 03:29 UTC
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.1.2

In previous years when I have used the Adldap2 framework to mess around with our Active Directory users, I had a specific need to modify the `msSFU30Password` attribute on certain users. This worked great with Adldap2, and it actually still works great in a test project on my dev machine. I just made a new project from scratch and tested it out to prove to myself I'm not crazy.

With the LdapRecord library, however, I am trying to do the same thing and I am getting the following exception:
```
LdapRecord\LdapRecordException
ldap_modify_batch(): Batch Modify: Server is unwilling to perform
```
I thought maybe it was a credential issue, but my aforementioned barebones test project that I setup using Adldap2 is using the exact same connection information. In Adldap2, this successfully sets that attribute:
```
$user->msSFU30Password = $new_password_hash;
$user->save()
```

Now, in the land of LdapRecord, I can't seem to translate this behavior over from Adldap2. If I get the User object (which is an instance of `LdapRecord\Models\ActiveDirectory\User`) and try to assign my new hash to the msSFU30Password attribute like above, I get the following error:
`ldap_modify_batch(): Batch Modify: Server is unwilling to perform `

I feel like that is misleading, though. I know I have the proper credentials and that those credentials have enough permissions to make the change. Since this works in Adldap2, was this capability (specifically, the ability to assign a value to a random attribute key, like $user->msSFU30Password = "something") not carried over to LdapRecord? Is there a different way to do it now that I haven't picked up on from the docs.

PS for Steve - While this behavior might be a bug, I realize I might be pushing up to the area of asking for support. I went to go sponsor your Github profile, and there was this weird thing where Github showed the following:
```
Total amount: $5.00 / year
Due today: $60.00
```
Not sure what's up with that, but it seemed backwards to me. Maybe I'm just having an off night when it comes to coding/Github :-P

**Comment by stevebauman** [comment] 2022-02-16 13:48
Hi @nspaul!

That's definitely strange, since Adldap2 and LdapRecord do share a bit of the same core.

> Since this works in Adldap2, was this capability (specifically, the ability to assign a value to a random attribute key, like $user->msSFU30Password = "something") not carried over to LdapRecord? Is there a different way to do it now that I haven't picked up on from the docs.

No, you're correct -- you set attributes the same way as you do in Adldap2.

Can you post your configuration with any sensitive details omitted?

> PS for Steve - While this behavior might be a bug, I realize I might be pushing up to the area of asking for support. I went to go sponsor your Github profile, and there was this weird thing where Github showed the following:

I'm not able to reproduce this through my GitHub sponsor dashboard preview. This is what I see:

![Screen Shot 2022-02-16 at 8 47 41 AM](https://user-images.githubusercontent.com/6421846/154277742-38a92ea5-cbad-4a1a-af03-fe17778bd836.png)

Do you see this as well?

**Comment by nspaul** [comment] 2022-02-16 16:13
Let me see if I can show a proper comparison here, with code. One thing I notice is that I am accessing the user object differently between the Adldap2 code and the LdapRecord code. That might have something to do with it, but I'm really not sure.

I don't want to introduce any red herrings here, but could it possible be that in the LdapRecord verison of my code, the User object resolves to a `LdapRecord\Models\ActiveDirectory\User` object, whereas it seems that the Adldap2 version resolves the user as a `Adldap\Models\User` object? If this is actually the root cause, what's the workaround?

Here is code snippet (it has been sanitized, and i didn't check it for inadvertent syntax errors) that effectively shows how I'm using the Adldap2 package, installed on my Mac, and it successfully changes the msSFU30Password attribute:
```
function change_sfu_password($username, $newpasswordhash)
    {
        $connection_config = [
            'hosts' => ['dc1.subdomain.domain.com'],
            'base_dn' => 'DC=subdomain,DC=domain,DC=com',
            'username' => 'account@subdomain.domain.com',
            'password' => 'accountpassword',
            'port' => 636,
            'use_ssl' => true,
        ];

        $adldap = new \Adldap\Adldap();
        $adldap->addProvider($connection_config);

        $provider = $adldap->connect();

        $results = $provider->search()->where('samaccountname', '=', $username)->get();

        $first = $results->first();

        $newpasswordhash = 'randomjunk' . rand(1, 20);
        $first->msSFU30Password = $newpasswordhash;
        
        if ($first->save()) {
            return true;
        } else {
            return false;
        }
    }
```

And then for my newer LdapRecord script, this is effectively what I'm doing (again, it's sanitized and not checked for inadvertent bugs):
```
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use LdapRecord\Models\ActiveDirectory\User;
use LdapRecord\Connection;
use LdapRecord\Container;

class MyClass extends Controller
{
    public function __construct()
    {
        $connection_domain_636 = new Connection([
            'hosts' => [getenv('CONNECTION_DOMAIN_636_HOSTS')],
            'base_dn' => getenv('CONNECTION_DOMAIN_636_BASE_DN'),
            'username' => getenv('CONNECTION_DOMAIN_636_USERNAME'),
            'password' => getenv('CONNECTION_DOMAIN_636_PASSWORD'),
            'port' => 636,
            'use_ssl' => true,
        ]);
        $connection_domain_636->connect();
        Container::addConnection($connection_domain_636, 'connection_domain_636');
    }

    public function change_sfu_password(string $username, string $currentPassword, string $newPasswordHash)
    {
        $connection = Container::getConnection('connection_domain_636');

        $searchForUser = User::where('samaccountname', '=', $username)->get();
        if ($searchForUser->count() == 1) {
            $user = $searchForUser->first();
        }

        $upn = $user->userprincipalname[0];

        if ( $connection->auth()->attempt($upn, $currentPassword, $stayAuthenticated = true) ) {
            $user->msSFU30Password = $newPasswordHash;
            $user->save();
        } else {
            dd('did not connect as user. probably bad password');
        }

        return false;
    }

    
}
```

I looked into the Github thing a little more. It seems that on my personal account, it shows the weirdness, but if I log into Github as my work account (also just a regular, free account), it shows correctly! Weird! FWIW, here is a screenshot of what I see when I try to sponsor you:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/812873/154307571-b95350bd-e557-4137-9e4f-8018f5a5688e.png">

**Comment by stevebauman** [comment] 2022-02-16 16:37
Is there a particular reason you're authenticating as the user to modify the `msSFU30Password` in LdapRecord but not in Adldap2?

```php
if ( $connection->auth()->attempt($upn, $currentPassword, $stayAuthenticated = true) ) {
```

Also that's really strange with the sponsorship program, I might have to contact GitHub to see what the issue is.

**Comment by nspaul** [comment] 2022-02-16 18:20
I guess there's not a technical reason. In the actual implementation of this code, I am changing this msSFU30Password attribute after having changed the actual password on the AD User. As part of that step (not shown here), I am confirming that the user has the correct credentials. In the big picture, however, maybe that's not even necessary, since the method call to change the user's `unicodepwd` attribute requires the old password and the new password.

That said, I just took out that part of my function, and I'm still getting the `ldap_modify_batch(): Batch Modify: Server is unwilling to perform` Exception.

To show the slightly modified function, as it stands now:
```
public function change_sfu_password(string $username, string $currentPassword, string $newPasswordHash) {
        $connection = Container::getConnection('connection_domain_636');

        $password_to_put = 'randomjunk' . rand(0, 20);

        $searchForUser = User::where('samaccountname', '=', $username)->get();
        if ($searchForUser->count() == 1) {
            $user = $searchForUser->first();
            $user->msSFU30Password = $password_to_put;
            $user->save();
        }
}
```

**Comment by stevebauman** [comment] 2022-02-16 19:21
Does the user come populated with the `msSFU30Password` attribute? Or is the property hidden like `unicodepwd`?

**Comment by nspaul** [comment] 2022-02-16 19:35
Update: Looking at this simplified version again, I realize I didn't set the connection on the $user. This is going to be necessary, because the connection determines which domain credentials to use. So the updated version looks more like this:

```
public function change_sfu_password(string $username, string $currentPassword, string $newPasswordHash) {
        $connection = Container::getConnection('connection_domain_636');

        $password_to_put = 'randomjunk' . rand(0, 20);

        $searchForUser = User::where('samaccountname', '=', $username)->get();
        if ($searchForUser->count() == 1) {
            $user = $searchForUser->first();
            $user->msSFU30Password = $password_to_put;
            $user->save();
        }
}
```

However, when I do it this way, the new Exception is this:
`ldap_modify_batch(): Batch Modify: Type or value exists`

To answer your question you asked while I was typing this response... When I run `var_dump($user->msSFU30Password);`, it returns null. Not sure what to make of that, except that it might be a hidden property, since it's not exactly a typical AD attribute.

**Comment by stevebauman** [comment] 2022-02-16 19:45
> Looking at this simplified version again, I realize I didn't set the connection on the $user

I'm not seeing that in the example posted?

Can we attempt modifying another user attribute first so we know that modification is actually working before stepping into the `msSFU30Password` attribute debugging?

For example, does this work?

```php
$user = $searchForUser->first();

$user->description = 'Foo bar';

$user->save();
```

**Comment by nspaul** [comment] 2022-02-17 01:24
(Sorry about not including the line to set the connection in my previous response. That's a result of me slightly tweaking this code as I post it, to make sure anything sensitive is removed, and I just got sloppy. I have edited the previous post to include that line)

Good idea. I just confirmed that I can indeed edit the description. I was also able to edit the givenname attribute (I picked that one somewhat randomly, knowing that it didn't really make much difference). This was done, as expected, with these lines:
```
$user->description = 'Something Something Something';
$user->givenname = 'Another Something';
```
When I then try to modify the msSFU30Password, I get the `ldap_modify_batch(): Batch Modify: Type or value exists` error.

I know we have really scoped down the ability of the admin account that I am using, so that it can only do so much damage if something goes rogue. So there is a chance it could simply not have enough permissions. But, from an AD standpoint, I know I have enough permissions because I'm using the same credentials in my Adldap project and it works just fine.

**Comment by nspaul** [comment] 2022-02-17 01:38
Update: Just for funsies, I switched my Connection over to use the credentials of a Domain Admin account. I would not do this in production, but it was worth the test. The end result is that I am seeing the same Exception while using DA creds to try and modify the msSFU30Password attribute.

`ldap_modify_batch(): Batch Modify: Type or value exists`

**Comment by stevebauman** [comment] 2022-02-17 01:38
Ok I have a couple things to try:

- Can you dump your users attributes to see if the `msSFU30Password` attribute key is present prior to modification?

```php
var_dump($user->getAttributes());
```

- Can you dump the users batch modifications in your Adldap2 dev repo after modifying the `msSFU30Password` attribute? I tested this locally with both Adldap2 and LdapRecord, and they both show the exact same modifications to be sent to the server:

```php
$user->msSFU30Password = 'foo';

var_dump($user->getModifications());

// array:1 [
//   0 => array:3 [
//     "attrib" => "mssfu30password"
//     "modtype" => 1
//     "values" => array:1 [
//       0 => "foo"
//     ]
//   ]
// ]
```

**Comment by nspaul** [comment] 2022-02-17 01:58
Absolutely!

User's attributes prior to modification in Adldap (i've sanitized a few properties):
```
array(80) {
  ["objectclass"]=>
  array(4) {
    [0]=>
    string(3) "top"
    [1]=>
    string(6) "person"
    [2]=>
    string(20) "organizationalPerson"
    [3]=>
    string(4) "user"
  }
  [0]=>
  string(11) "objectclass"
  ["cn"]=>
  array(1) {
    [0]=>
    string(9) "Test, Test"
  }
  [1]=>
  string(2) "cn"
  ["sn"]=>
  array(1) {
    [0]=>
    string(4) "Test"
  }
  [2]=>
  string(2) "sn"
  ["description"]=>
  array(1) {
    [0]=>
    string(68) "Account for testing"
  }
  [3]=>
  string(11) "description"
  ["givenname"]=>
  array(1) {
    [0]=>
    string(10) "TESTAA"
  }
  [4]=>
  string(9) "givenname"
  ["distinguishedname"]=>
  array(1) {
    [0]=>
    string(62) "CN=Test\, ISD,OU=myOU,OU=myOU2,DC=childdomain,DC=domain,DC=com"
  }
  [5]=>
  string(17) "distinguishedname"
  ["instancetype"]=>
  array(1) {
    [0]=>
    string(1) "4"
  }
  [6]=>
  string(12) "instancetype"
  ["whencreated"]=>
  array(1) {
    [0]=>
    string(17) "20190312151029.0Z"
  }
  [7]=>
  string(11) "whencreated"
  ["whenchanged"]=>
  array(1) {
    [0]=>
    string(17) "20220217014159.0Z"
  }
  [8]=>
  string(11) "whenchanged"
  ["displayname"]=>
  array(1) {
    [0]=>
    string(9) "Test, Test"
  }
  [9]=>
  string(11) "displayname"
  ["usncreated"]=>
  array(1) {
    [0]=>
    string(5) "38934"
  }
  [10]=>
  string(10) "usncreated"
  ["usnchanged"]=>
  array(1) {
    [0]=>
    string(9) "255583464"
  }
  [11]=>
  string(10) "usnchanged"
  ["name"]=>
  array(1) {
    [0]=>
    string(9) "Test, Test"
  }
  [12]=>
  string(4) "name"
  ["objectguid"]=>
  array(1) {
    [0]=>
    string(16) "ak��p��I�s��A�b"
  }
  [13]=>
  string(10) "objectguid"
  ["useraccountcontrol"]=>
  array(1) {
    [0]=>
    string(3) "512"
  }
  [14]=>
  string(18) "useraccountcontrol"
  ["badpwdcount"]=>
  array(1) {
    [0]=>
    string(1) "0"
  }
  [15]=>
  string(11) "badpwdcount"
  ["codepage"]=>
  array(1) {
    [0]=>
    string(1) "0"
  }
  [16]=>
  string(8) "codepage"
  ["countrycode"]=>
  array(1) {
    [0]=>
    string(1) "0"
  }
  [17]=>
  string(11) "countrycode"
  ["badpasswordtime"]=>
  array(1) {
    [0]=>
    string(18) "132894119226403337"
  }
  [18]=>
  string(15) "badpasswordtime"
  ["lastlogoff"]=>
  array(1) {
    [0]=>
    string(1) "0"
  }
  [19]=>
  string(10) "lastlogoff"
  ["lastlogon"]=>
  array(1) {
    [0]=>
    string(18) "132894119448838712"
  }
  [20]=>
  string(9) "lastlogon"
  ["pwdlastset"]=>
  array(1) {
    [0]=>
    string(18) "132894119420970932"
  }
  [21]=>
  string(10) "pwdlastset"
  ["primarygroupid"]=>
  array(1) {
    [0]=>
    string(3) "513"
  }
  [22]=>
  string(14) "primarygroupid"
  ["objectsid"]=>
  array(1) {
    [0]=>
    string(28) "x�yZ$�R�$"
  }
  [23]=>
  string(9) "objectsid"
  ["accountexpires"]=>
  array(1) {
    [0]=>
    string(1) "0"
  }
  [24]=>
  string(14) "accountexpires"
  ["logoncount"]=>
  array(1) {
    [0]=>
    string(1) "0"
  }
  [25]=>
  string(10) "logoncount"
  ["samaccountname"]=>
  array(1) {
    [0]=>
    string(7) "isdtest"
  }
  [26]=>
  string(14) "samaccountname"
  ["samaccounttype"]=>
  array(1) {
    [0]=>
    string(9) "805306368"
  }
  [27]=>
  string(14) "samaccounttype"
  ["userprincipalname"]=>
  array(1) {
    [0]=>
    string(24) "mytestusername@child.domain.com"
  }
  [28]=>
  string(17) "userprincipalname"
  ["objectcategory"]=>
  array(1) {
    [0]=>
    string(51) "CN=Person,CN=Schema,CN=Configuration,DC=domain,DC=com"
  }
  [29]=>
  string(14) "objectcategory"
  ["dscorepropagationdata"]=>
  array(5) {
    [0]=>
    string(17) "20220112143448.0Z"
    [1]=>
    string(17) "20211202195829.0Z"
    [2]=>
    string(17) "20211105190214.0Z"
    [3]=>
    string(17) "20211105173845.0Z"
    [4]=>
    string(17) "16010714223649.0Z"
  }
  [30]=>
  string(21) "dscorepropagationdata"
  ["lastlogontimestamp"]=>
  array(1) {
    [0]=>
    string(18) "132894119448838712"
  }
  [31]=>
  string(18) "lastlogontimestamp"
  ["mail"]=>
  array(1) {
    [0]=>
    string(35) "paul.brown@company.com"
  }
  [32]=>
  string(4) "mail"
  ["mssfu30loginshell"]=>
  array(1) {
    [0]=>
    string(13) "/sbin/nologin"
  }
  [33]=>
  string(17) "mssfu30loginshell"
  ["mssfu30password"]=>
  array(1) {
    [0]=>
    string(12) "randomjunk91"
  }
  [34]=>
  string(15) "mssfu30password"
  ["mssfu30nisdomain"]=>
  array(1) {
    [0]=>
    string(4) "myshortdomain"
  }
  [35]=>
  string(16) "mssfu30nisdomain"
  ["mssfu30name"]=>
  array(1) {
    [0]=>
    string(7) "testtest"
  }
  [36]=>
  string(11) "mssfu30name"
  ["mssfu30uidnumber"]=>
  array(1) {
    [0]=>
    string(5) "63001"
  }
  [37]=>
  string(16) "mssfu30uidnumber"
  ["mssfu30gidnumber"]=>
  array(1) {
    [0]=>
    string(5) "63001"
  }
  [38]=>
  string(16) "mssfu30gidnumber"
  ["mssfu30homedirectory"]=>
  array(1) {
    [0]=>
    string(13) "/home/testtest"
  }
  [39]=>
  string(20) "mssfu30homedirectory"
}
```

Now the user's attributes prior to modification in LdapRecord (i used dd() since this is Laravel):
```
array:26 [[▼]()
  "objectclass" => array:4 [[▼]()
    0 => "top"
    1 => "person"
    2 => "organizationalPerson"
    3 => "user"
  ]
  "cn" => array:1 [[▼]()
    0 => "Test, Test"
  ]
  "sn" => array:1 [[▼]()
    0 => "Test"
  ]
  "description" => array:1 [[▼]()
    0 => "Account for testing"
  ]
  "givenname" => array:1 [[▼]()
    0 => "TESTAA"
  ]
  "distinguishedname" => array:1 [[▼]()
    0 => "CN=Test\, ISD,OU=myOU,OU=myOU2,DC=childdomain,DC=domain,DC=com"
  ]
  "instancetype" => array:1 [[▼]()
    0 => "0"
  ]
  "whencreated" => array:1 [[▼]()
    0 => "20190312151029.0Z"
  ]
  "whenchanged" => array:1 [[▼]()
    0 => "20220217013738.0Z"
  ]
  "displayname" => array:1 [[▼]()
    0 => "Test, Test"
  ]
  "usncreated" => array:1 [[▼]()
    0 => "240737"
  ]
  "usnchanged" => array:1 [[▼]()
    0 => "80520866"
  ]
  "name" => array:1 [[▼]()
    0 => "Test, Test"
  ]
  "objectguid" => array:1 [[▼]()
    0 => b"akåÙpÕöI­sÁ \x1CAÌb"
  ]
  "useraccountcontrol" => array:1 [[▼]()
    0 => "512"
  ]
  "pwdlastset" => array:1 [[▼]()
    0 => "132894119420970932"
  ]
  "primarygroupid" => array:1 [[▼]()
    0 => "513"
  ]
  "objectsid" => array:1 [[▼]()
    0 => b"\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\x11\x02xþyZ\x05$”RÅ\f\x1C$\x00\x00"
  ]
  "accountexpires" => array:1 [[▼]()
    0 => "0"
  ]
  "samaccountname" => array:1 [[▼]()
    0 => "testtest"
  ]
  "samaccounttype" => array:1 [[▼]()
    0 => "805306368"
  ]
  "userprincipalname" => array:1 [[▼]()
    0 => "testtest@childdomain.domain.com"
  ]
  "objectcategory" => array:1 [[▼]()
    0 => "CN=Person,CN=Schema,CN=Configuration,DC=domain,DC=com"
  ]
  "dscorepropagationdata" => array:5 [[▼]()
    0 => "20220112143625.0Z"
    1 => "20211202195232.0Z"
    2 => "20211105190355.0Z"
    3 => "20211105173533.0Z"
    4 => "16010714223649.0Z"
  ]
  "lastlogontimestamp" => array:1 [[▼]()
    0 => "132894119448838712"
  ]
  "mail" => array:1 [[▼]()
    0 => "paul.brown@company.com"
  ]
]
```

And finally, the modifications of the user after modifying the `msSFU30Password` attribute in the Adldap2 test project:
```
array(1) {
  [0]=>
  array(3) {
    ["attrib"]=>
    string(15) "mssfu30password"
    ["modtype"]=>
    int(3)
    ["values"]=>
    array(1) {
      [0]=>
      string(10) "randomjunk"
    }
  }
}
```

**Comment by stevebauman** [comment] 2022-02-17 02:13
Strange, for some reason all of the attributes aren't being returned from the LdapRecord query... 

Can you manually select the `mssfu30password` attribute on the LdapRecord user query and see if it is returned in the users attributes?

Example:

```php
$user = User::where('samaccountname', '=', $username)->select('mssfu30password')->first();

var_dump($user->getAttributes());
```

This would be the reason why Adldap2 is working and LdapRecord is not.

Since the attribute is not present in the LdapRecord result, LdapRecord will assume it's a new attribute and use a modtype of `1` (`LDAP_MODIFY_BATCH_ADD`). With Adldap2, it's visible, so it will flip to using modtype `3` (`LDAP_MODIFY_BATCH_REPLACE`).

**Comment by nspaul** [comment] 2022-02-17 13:16
I modified my code to manually select `mssfu30password` and it gave an interesting result. I assumed it would just return all of the user's attributes, but it really just returned no attributes. Specifically, here is the result:

```
array:2 [[▼]()
  "objectclass" => array:4 [[▼]()
    0 => "top"
    1 => "person"
    2 => "organizationalPerson"
    3 => "user"
  ]
  "objectguid" => array:1 [[▼]()
    0 => b"akåÙpÕöI­sÁ \x1CAÌb"
  ]
]
```

And yes, I just double/triple checked... I am using the same credentials.

**Comment by stevebauman** [comment] 2022-02-17 13:31
Ok thanks for confirming that @nspaul, I appreciate your help narrowing this down so I can fix this if this is indeed a bug in LdapRecord.

Can you do a dump on the query in Adldap2 and LdapRecord to see if they have the same filters? The API is the similar on both:

**Adldap2**:

```php
$filter = $provider->search()->where('samaccountname', '=', $username)->getUnescapedQuery();

var_dump($filter);
```

**LdapRecord**:

```php
$filter = User::where('samaccountname', '=', $username)->getUnescapedQuery();

var_dump($filter);
```

**Comment by nspaul** [comment] 2022-02-17 13:44
Adldap2 (username sanitized):
`string(24) "(samaccountname=testtest)"`

LdapRecord (username sanitized):
`string(141) "(&(objectclass=top)(objectclass=person)(objectclass=organizationalperson)(objectclass=user)(samaccountname=testtest)(!(objectclass=computer)))"'

Both projects are on my local Mac. I put them both in my ~/Sites folder, and I have Laravel Valet hosting the sites out under the <foldername>.test URL. In that sense, I'm just letting Valet do its thing, so they should both be effectively running in the identical environment.

PS - I just went ahead and hit the sponsorship button. I figured that it was overdue on my part... your libraries have helped me out tremendously, and you are such an asset to the community.
I can't make complete sense of it, but it appears that it just made me pay for a year's worth of sponsorship, because my invoice says my next payment is a year from now. ¯\_(ツ)_/¯.

**Comment by stevebauman** [comment] 2022-02-17 13:55
Thank you @nspaul! I really appreciate that! 😄  That's so weird about the sponsorship, I'm not sure why it would be different on your end.

Hmmm, we're getting closer!

Can you try using the `Entry` model to dump the users attributes instead inside your LdapRecord project so we can remove the `User` model from the equation?

```php
use LdapRecord\Models\Entry;

$attributes = Entry::where('samaccountname', '=', $username)->first()->getAttributes();

var_dump($attributes);
```

**Comment by nspaul** [comment] 2022-02-17 14:06
Yeah I'm still wondering about the `User` model thing. Since it is using the `ActiveDirectory\User` model, it makes me wonder if there's some "magic" that is hiding any of the unusual attributes, such as `msSFU30Password`. Anyway, here's the result of querying the object as an `Entry` in the LdapRecord project:

```
array:26 [[▼]()
  "objectclass" => array:4 [[▼]()
    0 => "top"
    1 => "person"
    2 => "organizationalPerson"
    3 => "user"
  ]
  "cn" => array:1 [[▼]()
    0 => "Test, Test"
  ]
  "sn" => array:1 [[▼]()
    0 => "Test"
  ]
  "description" => array:1 [[▼]()
    0 => "Account for testing"
  ]
  "givenname" => array:1 [[▼]()
    0 => "TESTAA"
  ]
  "distinguishedname" => array:1 [[▼]()
    0 => "CN=Test\, Test,OU=service,OU=Accounts,DC=child,DC=company,DC=com"
  ]
  "instancetype" => array:1 [[▼]()
    0 => "0"
  ]
  "whencreated" => array:1 [[▼]()
    0 => "20190312151029.0Z"
  ]
  "whenchanged" => array:1 [[▼]()
    0 => "20220217013738.0Z"
  ]
  "displayname" => array:1 [[▼]()
    0 => "Test, Test"
  ]
  "usncreated" => array:1 [[▼]()
    0 => "240737"
  ]
  "usnchanged" => array:1 [[▼]()
    0 => "80520866"
  ]
  "name" => array:1 [[▼]()
    0 => "Test, Test"
  ]
  "objectguid" => array:1 [[▼]()
    0 => b"akåÙpÕöI­sÁ \x1CAÌb"
  ]
  "useraccountcontrol" => array:1 [[▼]()
    0 => "512"
  ]
  "pwdlastset" => array:1 [[▼]()
    0 => "132894119420970932"
  ]
  "primarygroupid" => array:1 [[▼]()
    0 => "513"
  ]
  "objectsid" => array:1 [[▼]()
    0 => b"\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\x11\x02xþyZ\x05$”RÅ\f\x1C$\x00\x00"
  ]
  "accountexpires" => array:1 [[▼]()
    0 => "0"
  ]
  "samaccountname" => array:1 [[▼]()
    0 => "testtest"
  ]
  "samaccounttype" => array:1 [[▼]()
    0 => "805306368"
  ]
  "userprincipalname" => array:1 [[▼]()
    0 => "testtest@childdomain.company.com"
  ]
  "objectcategory" => array:1 [[▼]()
    0 => "CN=Person,CN=Schema,CN=Configuration,DC=company,DC=com"
  ]
  "dscorepropagationdata" => array:5 [[▼]()
    0 => "20220112143625.0Z"
    1 => "20211202195232.0Z"
    2 => "20211105190355.0Z"
    3 => "20211105173533.0Z"
    4 => "16010714223649.0Z"
  ]
  "lastlogontimestamp" => array:1 [[▼]()
    0 => "132894119448838712"
  ]
  "mail" => array:1 [[▼]()
    0 => "paul.brown@company.com"
  ]
]
```

**Comment by stevebauman** [comment] 2022-02-17 14:38
Can you confirm the version of LdapRecord are you using @nspaul?

**Comment by nspaul** [comment] 2022-02-17 14:41
From the composer.lock file:
```
"name": "directorytree/ldaprecord",
"version": "v2.9.2",
```

FWIW, it got installed with ldaprecord-laravel. That version is at 2.5.3:
```
"name": "directorytree/ldaprecord-laravel",
"version": "v2.5.3",
```

**Comment by stevebauman** [comment] 2022-02-17 15:03
Ohh I see, so you're LdapRecord-Laravel.

Can you post your entire LdapRecord example again? This seems to be connection driven, since you're adding a connection dynamically, but also using LdapRecord-Laravel which provides you connections via the `config/ldap.php` configuration file.

I'm thinking the models are actually using a default LDAP connection you may have configured in your Laravel application, but we're making an assumption that they're using this dynamically created connection, which is not the case.

Do you have any connections configured inside of your `config/ldap.php` file or inside of your `.env`?

**Comment by stevebauman** [comment] 2022-02-17 15:05
For example, you're switching connections here:

```php
 $user->setConnection('connection_domain_636');
```

But the user has already been retrieved, and the `msSFU30Password` would be missing from the users attributes.

Try the following:

```php
$attributes = User::on('connection_domain_636')->where('samaccountname', '=', $username)->getAttributes();

var_dump($attributes);
```

**Comment by stevebauman** [comment] 2022-02-17 15:29
Ah excellent! I'm so glad we've found the issue. No worries at all @nspaul! 😄 

I'll close this out, but let me know if you encounter any further issues and I'd be happy to help.

**Closed by stevebauman** 2022-02-17 15:29 UTC
Labels: bug
