### ISSUE TITLE
[Feature] Include mailbox creation functionality?

### ISSUE THREAD

**Issue by grantholle** [DirectoryTree/LdapRecord#176] opened 2020-07-14 05:53 UTC
So after much toil (and help from you) I have mailbox creation working. Emphasis on toil.

Would it be worth including mailbox creation in the `User` model? At the very least I plan to submit a page for the documentation describing how to create a mailbox.

Something like

```php
$user = (new User)->inside('ou=Users,dc=local,dc=com')->withMailbox();

// etc

$user->save();
// or
$user->saveWithMailbox();
```

and that would add some of the fields needed to create the mailbox (similar to how LdapTools does it).

Worth it or no? I could send in a PR for you to review.

Kind of separate question, I've found that I have to save the user 3 times before it's created "right."

1. All the default attributes.
2. Setting `userAccountControl`
3. Setting `pwdlastset`

For some reason I can't combine 2 + 3. If I do, `pwdlastset` seems to have no effect and I'm not required to change the password. Is that normal/expected behavior?

**Comment by stevebauman** [comment] 2020-07-14 15:54
Hey @grantholle!

I agree with you that this should be included in the core. I'd love to make the API as simple and clean as possible.

However, this may be tricky since I don't have the ability to create exchange mailboxes in my environment. If you're up for the task of creating the API, testing, and creating the actual PHPUnit tests, then I'd gladly accept PR's for it!

> For some reason I can't combine 2 + 3. If I do, pwdlastset seems to have no effect and I'm not required to change the password. Is that normal/expected behavior?

Are you able to share the code on how you're performing it? I believe you should be able to set it to `0` (which toggles the "User must change password at next logon".) during the `userAccountControl` update.

**Comment by grantholle** [comment] 2020-07-15 01:45
Yeah, it's really weird. After testing a bunch of scenarios for this comment I've realized that setting `userAccountControl` puts a value in `pwdlastset`. I can create the user with `pwdlastset = 0` on the first go and create the user (and never update) and it gets created with a value of `never`. As soon as I enable the account with `userAccountControl` or save it without saving any additional attributes it puts a timestamp for `pwdlastset`. It has to be the _third_ time. Very strange behavior. Here is my full code:

```php
$ldapUser = (new LdapUser)->inside($this->entity->organizational_unit);
$ldapUser->givenName = $this->first_name;
$ldapUser->sn = $this->last_name;
$ldapUser->cn = $this->display_name;
$ldapUser->displayName = $this->display_name;
$ldapUser->name = $this->display_name;
$ldapUser->title = $this->title;
$ldapUser->department = $this->department;
$ldapUser->manager = $this->supervisor_dn;
$ldapUser->unicodePwd = $this->temp_password;
$ldapUser->samaccountname = $this->username;
$ldapUser->mailNickname = $this->username;
$ldapUser->mail = $this->email;
$ldapUser->userPrincipalName = $this->email;
$ldapUser->company = $this->entity->company_name;
$ldapUser->streetAddress = $this->entity->address;
$ldapUser->l = $this->entity->city;
$ldapUser->st = $this->entity->state;
$ldapUser->c = $this->entity->country;
$ldapUser->postalCode = $this->entity->zip;
$ldapUser->wWWHomePage = $this->entity->website;
$ldapUser->telephoneNumber = $this->entity->phone;

// Exchange attributes
// The logic was ported from LdapTools
$ldapUser->msExchHomeServerName = $this->getExchangeServerDn();
$ldapUser->legacyExchangeDN = $this->getLegacyExchangeDn();
$ldapUser->homeMDB = $this->getExchangeDatabaseDn();
$ldapUser->mDBUseDefaults = 'TRUE';
$ldapUser->msExchUserCulture = 'en-US';
$ldapUser->proxyAddresses = "SMTP:{$this->email}";
$ldapUser->msExchMailboxGUID = (new GUID(Uuid::uuid4()))->toBinary();
$ldapUser->msExchUserAccountControl = 0;
$ldapUser->msExchRecipientDisplayType = 1073741824;
$ldapUser->msExchRBACPolicyLink = $this->getExchangeRbacPolicyDn();
$ldapUser->msExchRecipientTypeDetails = 1;
$ldapUser->msExchVersion = 88218628259840;
$ldapUser->showInAddressBook = $this->getAddressBookDns();
$ldapUser->msExchPoliciesIncluded = $this->getRecipientPolicyDn();

// Save the user initially
$ldapUser->save();

// Enable their account
$ldapUser->userAccountControl = 512;
$ldapUser->save();

// Force reset when the log in
$ldapUser->pwdlastset = 0;
$ldapUser->save();
```

Doing `$ldapUser->pwdlastset = 0` in the same step of `userAccountControl` has a populated value of the time I created the account for `pwdlastset` in AD and doesn't make me change my password. I have also tested doing it without enabling their account and saving `pwdlastset` during the second save, but the timestamp is still populated.

```php
// Save the user initially
$ldapUser->save();

// Enable their account
// $ldapUser->userAccountControl = 512;
// $ldapUser->save();

// Force reset when the log in
$ldapUser->pwdlastset = 0;
$ldapUser->save();
```

However, doing it on the third save sets `pwdlastset` to `never`, even without updating any attributes.

```php
// Save the user initially
$ldapUser->save();

// Enable their account
// $ldapUser->userAccountControl = 512;
$ldapUser->save();

// Force reset when the log in
$ldapUser->pwdlastset = 0;
$ldapUser->save();
```

**Comment by stevebauman** [comment] 2020-10-24 20:23
Hi @grantholle, apologies for the very long delay in response.

To my knowledge, this is due to Active Directory and how it functions. LdapRecord isn't doing anything behind the scenes here. It's simply sending attribute updates.

Closing as this Active Directory related, and not a bug or issue with LdapRecord itself.

**Closed by stevebauman** 2020-10-24 20:23 UTC
Labels: enhancement
